version: '3.8'

services:
  central-control-dev:
    container_name: central-control-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${INTERNAL_PORT:-3000}
    ports:
      - "${PORT:-3000}:${INTERNAL_PORT:-3000}"
      - "9249:9229"
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - NODE_ENV=development
    command: npm run dev

  postgres:
    image: postgres:16-alpine
    container_name: central-control-postgres
    restart: always
    ports:
      - "${DATABASE_PORT:-5432}:${DATABASE_INTERNAL_PORT:-5432}"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-central_control}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 