services:
  control-center:
    container_name: control-center
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${INTERNAL_PORT:-3000}
    ports:
      - "${PORT:-3000}:${INTERNAL_PORT:-3000}"
      - "9250:9229"
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

  postgres:
    image: postgres:16-alpine
    container_name: central-control-postgres
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-central_control}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  k6:
    image: ghcr.io/grafana/xk6-dashboard:0.7.2
    container_name: k6
    volumes:
      - ./tests/performance:/tests/performance
      - ./k6-results:/home/k6
    ports:
      - "${K6_PORT:-5665}:5665"
    environment:
      BASE_URL: "http://host.docker.internal:${PORT:-3000}"
      K6_WEB_DASHBOARD_EXPORT: "report.html"
      K6_WEB_DASHBOARD_PERIOD: "1s"
      K6_WEB_DASHBOARD_OPEN: "true"
    command: [
      "run",
      "--out", "web-dashboard",
      "/tests/performance/contexts/users/get-users.mjs"
    ]

volumes:
  postgres_data: 